### ISSUE TITLE
 Commands do not respond

### ISSUE THREAD

**Issue by VincePaul** [adamyi/notes_to_keep#3]
Hi,

None of the command respond. My system replies "unknown command".

Command not working:
    notes_to_keep <email> <password> [options]
    notes_to_keep --help
    notes_to_keep --version

**Comment by adamyi** [comment]
This appears to be a PATH issue. How did you install notes_to_keep? Did you install it with pip or clone the source code with git? You will probably get no output if you run `which notes_to_keep`?

**Comment by adamyi** [comment]
I'll close this for now. Let me know if the issue still exists.
