### ISSUE TITLE
Getting an error while pip install

### ISSUE THREAD

**Issue by fr0stnk** [adamyi/notes_to_keep#4]
As you can see, I'm getting error "Could not find a version that satisfies the requirement notes_to_keep (from versions: )
No matching distribution found for notes_to_keep", can you fix it?
![image](https://user-images.githubusercontent.com/10252136/46915065-ddf6d380-cfae-11e8-8b01-9099e4e0c5f8.png)

**Comment by adamyi** [comment]
It appears to be an issue with verifying HTTPS SSL certificate. You will probably run into an error if you run `curl https://pypi.python.org`. Can you check your local ca certificate settings?

**Comment by adamyi** [comment]
I'll close this for now. Let me know if the issue still exists.
