### ISSUE TITLE
Not able to run - no module named docopt

### ISSUE THREAD

**Issue by egglikelolly** [adamyi/notes_to_keep#5]
Hi there,

trying to move all my mac notes to google keep, this is the only thing I've come across that doesn't require me manually copying everything!

I'm not super familiar with python so I may have made some mistakes. I assume I just have to add my google account email and passwork in the  "notes_to_keep.py" to get it to work. When I run it i get this error message back

>  File ".../notes_to_keep-master/notes_to_keep/notes_to_keep.py", line 31, in <module>
>     from docopt import docopt
> ModuleNotFoundError: No module named 'docopt'

I also tried running "setup.py" and I get this error message

> Warning (from warnings module):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 261
>     warnings.warn(msg)
> UserWarning: Unknown distribution option: 'long_description_content_type'

any advice in laymen's terms would be greatly appreciated. I don't really fancy manually copying and pasting all my notes from my mac to google keep.

**Comment by adamyi** [comment]
notes_to_keep depends on 3rd-party libraries to work. So you need to install those dependencies.

One way to do that is to install notes_to_keep using pip: run `pip install notes_to_keep`. pip is a common Python package management system (like apt, npm, etc.) It will automatically install missing dependencies.

If you prefer cloning the source code. You could try using `python setup.py install`. The warning about `long_description_content_type` can be ignored.
