### ISSUE TITLE
Multiple duplicates of notes with attachments are imported (one per attachment on the note)

### ISSUE THREAD

**Issue by chadlavi** [adamyi/notes_to_keep#6]
I'm running this with python 3.7, and getting multiple duplicates some notes when importing. For example, I have 1 note called "Zojirushi steel cut oats", but I ended up with 6 copies of it in Keep. Similarly, I have one note called "Castella cake," but I ended up with 10 copies of it in Keep.

Here is the header info in Keep for the "Zojirushi" notes, note that these are all imported from the same note.

![screenshot 2019-01-01 22 31 59](https://user-images.githubusercontent.com/7226642/50579692-5b471d00-0e15-11e9-822f-3f40e851e055.png)

Here's the full output of note imports before I stopped the program. Note that of the 7 notes that were imported, 3 of them had many copies.

![screenshot 2019-01-01 22 32 31](https://user-images.githubusercontent.com/7226642/50579691-5b471d00-0e15-11e9-9555-a0f7e4e6b070.png)

Here's the header info in Keep for the "Castella" notes. Note that these, too, are from the same original note in my Notes db. 

![screenshot 2019-01-01 22 33 04](https://user-images.githubusercontent.com/7226642/50579690-5b471d00-0e15-11e9-9405-d79ba85f2830.png)

It seems like this is related to attachments--the Zojirushi note has 6 attachments; the "design needs" note that you can see from the log, which had 3 copies created, had 3 attachments. The Castella note had 12 attachments, so I assume if I had let the app run to completion I would have ended up with 2 additional copies of that note in Keep. 

*UPDATE FOR CLARITY*: I installed this locally with `pip3.7 install -e notes-to-keep/`, and tried editing a few things to get the behavior I wanted.

**Comment by adamyi** [comment]
Thanks for reporting. The SQL statement used to fetch the notes from db joined the attachment table, leading to duplicate rows. Since the attachment is not used for uploading, I removed them in the code. Let me know if c4036f4 fixed this

**Comment by chadlavi** [comment]
Thanks! I'll check this out this evening. 

Chad Lavimoniere

**Comment by adamyi** [comment]
I'll close this for now. Feel free to re-open it if the issue still exists.
