### ISSUE TITLE
remove notes_to_keep content meta data on imported notes

### ISSUE THREAD

**Issue by lindhard** [adamyi/notes_to_keep#8]
Since all the new keep notes have a label attached that differentiate them, why add the extra text to the imported note?
Import the note as clean as possible to resemble the notes world and thereby making the transition smoother for the end user.

So in gkeep.py, instead of:

`return "Imported from Apple Note\nOriginal Create Time: %s\nImport Time: %s\n-----------------------\n%s\n-----------------------\nhttps://github.com/adamyi/notes_to_keep" % (note.date_created.strftime("%c"), datetime.now().strftime("%c"), parseHTML(note.data))`

then 

`return parseHTML(note.data)`

**Comment by adamyi** [comment]
It contains the original creation time of the note in iCloud (besides import time as indicated in the label), which is not included in the label. If you use the `--no-time` parameter. this header message will not be added to the note.

**Comment by adamyi** [comment]
I do agree that it's better not to include this header by default, and change it to `--include-original-time`.
