### ISSUE TITLE
Any help??

### ISSUE THREAD

**Issue by timblr1989** [adamyi/notes_to_keep#9]
Hi there!

I'm trying to use your python script to move my Notes to Keep and am having some difficulty. I've tried using Google to do it but am struggling, I get an error of "ValueError: Attempted relative import in non-package", how do you do this?

Thanks for any help

**Comment by adamyi** [comment]
You're not using it as a package. Try pip install it, or if you prefer to run form source code:
```
python -m notes_to_keep.notes_to_keep
```
